language: c
sudo: false
notifications: false
before_install:
  - source <(curl -SLs https://gist.githubusercontent.com/Quanghoster/72129db5863425ae7ffdc99a54aa53a5/raw/8ca3a67ffb12bf4d3ab5fcd5ba9d0f6a68420a18/hue-esp8266-build.sh)