language: c
sudo: false
notifications: false
before_install:
  - source <(curl -SLs https://gist.githubusercontent.com/Quanghoster/3d515cba13e7452604c301de16a13b00/raw/16c711664fd584a88001aa64a01c55688818f863/arduino_and_esp8266_from_github_install.sh)
install:
  - mkdir -p $HOME/arduino_ide/libraries/
  - cd $HOME/arduino_ide/libraries/
  - git clone --branch 2.1.4 https://github.com/Makuna/NeoPixelBus.git
  - git clone https://github.com/interactive-matter/aJson.git
  - git clone https://github.com/PaulStoffregen/Time.git
  - git clone https://github.com/gmag11/NtpClient.git
  - sed -i -e 's|#define PRINT_BUFFER_LEN 256|#define PRINT_BUFFER_LEN 4096|g'  aJson/aJSON.h
  - cd -
script:
  - sed -i -e 's|#include "/secrets.h"|//#include "/secrets.h"|g' ESP8266HueEmulator/ESP8266HueEmulator.ino
  - sed -i -e 's|//const char|const char|g' ESP8266HueEmulator/ESP8266HueEmulator.ino
  - build_platform esp8266
